# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Bind workspaces to monitors based on current topology (solo / office / home)
exec-once = omarchy-workspace-topology

# Preset work layout
exec-once = [workspace 1 silent] omarchy-launch-browser
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec
exec-once = omarchy-workspace3-layout
exec-once = [workspace 4 silent] uwsm-app -- code
exec-once = [workspace 5 silent] uwsm-app -- obsidian
exec-once = [workspace 6 silent] uwsm-app -- xdg-terminal-exec
